spring.application.name=jiro-tasks
springdoc.swagger-ui.path=/swagger-ui
server.port=8086

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/jiro_task
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}

app.url=http://localhost:8087/api/v1